### ISSUE TITLE
Decouple templates from the from-template package

### ISSUE THREAD

**Issue by countvajhula** [racket-templates/racket-templates#7]
It would also be nice if older versions of `from-template` could still access newly added templates without requiring a `raco pkg update from-template`.

One way could be to extract the actual registry of templates into a separate repo from this one, which is queried dynamically by installed versions of racket-template.

Example sequence:
1. User installs `from-template`
2. Someone adds a new template `fancy-template` to the repo
3. User runs `raco new --list`

`fancy-template` should ideally appear in the list, and should be installable, even though the user installed `from-template` before that template was added to the registry.

**Comment by nixin72** [comment]
You don't need to update `from-template` every time a new template is added. Doing `raco new` will use the \*GitHub API to get the names of all the templates and then will use `https://raw.githubusercontent.com/` to extract the actual template data. 

You might not be getting the data right away because raw.githubusercontent does take a little bit to get the new contents of a file when you push to GitHub. If you're having issues with it just not appearing at all, that's a bug and once again my fault :sweat_smile: I need to get proper tests set up for this and there's already an issue open to include some CI.

\* I'm going to be changing this a little bit since an individual request for each template is pretty slow, so CI needs to get added to this repository to generate an artifact that contains a list of the templates that can easily be pulled down once instead of each template individually.

**Comment by countvajhula** [comment]
Ah okay, I just assumed they were coupled because they're in the same repo. All good, then!

**Comment by nixin72** [comment]
The actual repository for the `from-template` tool is https://github.com/nixin72/from-template, not this one @countvajhula

**Comment by countvajhula** [comment]
@nixin72 Oh I see, perfect!
